In [15]:
import numpy as np

In [16]:
a = np.array([4, 10, 12, 23, -2, -1, 0, 0, 0, -6, 3, -7])


In [ ]:
# How many negative numbers are there?
a[(a < 0)]


In [ ]:
len(a[(a < 0)])   # 4 negative numbers

In [ ]:
# How many positive numbers are there?

a[(a > 0)]

In [ ]:
# How many even positive numbers are there?

len(a[(a > 0)]) 

In [ ]:
# If you were to add 3 to each data point, how many positive numbers would there be?

new_number = a + 3

In [ ]:
new_number

In [ ]:
len(a[a > 0])

In [ ]:
# If you squared each number, what would the new mean and standard deviation 
squared = a ** 2

In [ ]:
# new mean and standard deviation respectively
np.mean(squared), np.std(squared)

In [ ]:
a

In [ ]:
# this is the mean and standard deviation for original array
np.mean(a), np.std(a)

In [ ]:
# A common statistical operation on a dataset is centering. 
# This means to adjust the data such that the mean of the data is 0. 
# This is done by subtracting the mean from each data point. Center the data set
a

In [ ]:
[a - np.mean(a)]

In [ ]:
#Calculate the z-score for each data point. Recall that the z-score is given by:

z_score = [(a -np.mean(a))/ np.std(a)]

In [ ]:
z_score

In [65]:
#Copy the setup and exercise directions from More Numpy Practice into your numpy_exercises.py 
#and add your solutions.



import numpy as np


In [66]:
a = np.array ([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

In [81]:
# Exercise 1 - Make a variable called sum_of_a to hold the sum of all the numbers in above list

sum_of_a = np.sum(a)
print(sum_of_a)

55


In [82]:
# Exercise 2 - Make a variable named min_of_a to hold the minimum of all the numbers in the above list

min_of_a = np.min(a)

print(min_of_a)

1


In [83]:
# Exercise 3 - Make a variable named max_of_a to hold the max number of all the numbers in the above list

max_of_a = np.max(a)
print(max_of_a)

10


In [84]:
# Exercise 4 - Make a variable named mean_of_a to hold the average of all the numbers in the above list
mean_of_a = np.mean(a)
print(mean_of_a)

5.5


In [85]:
# Exercise 5 - Make a variable named product_of_a to hold the product of multiplying all the numbers in the above list together
product_of_a = np.product(a)
print(product_of_a)


3628800


In [80]:
# Exercise 6 - Make a variable named squares_of_a. It should hold each number in a squared like [1, 4, 9, 16, 25...]

squares_of_a = np.square(a)
print(squares_of_a)


[  1   4   9  16  25  36  49  64  81 100]


In [78]:
# Exercise 7 - Make a variable named odds_in_a. It should hold only the odd numbers
odds_in_a = a[a%2 !=0]
print(odds_in_a)


[1 3 5 7 9]


In [76]:
# Exercise 8 - Make a variable named evens_in_a. It should hold only the evens.
evens_in_a = a[a%2 == 0]
print(evens_in_a)

[ 2  4  6  8 10]


In [88]:
# #Setup 2: Consider what it would take to find the sum, min, max, average, sum, product, and list of squares for this list of two lists.
b = np.array([
    [3, 4, 5],
    [6, 7, 8]
])

In [94]:
# # Exercise 1 - refactor the following to use numpy. Use sum_of_b as the variable. **Hint, you'll first need to make sure that the "b" variable is a numpy array**
# sum_of_b = 0
# for row in b:
#     sum_of_b += sum(row)

# print(sum_of_b)
sum_of_b = np.sum(b)
print(sum_of_b)

33


In [96]:
# Exercise 2 - refactor the following to use numpy. 
# min_of_b = min(b[0]) if min(b[0]) <= min(b[1]) else min(b[1])  
min_of_b = np.min(b)
print(min_of_b)

3


In [105]:
# # Exercise 3 - refactor the following maximum calculation to find the answer with numpy.
# max_of_b = max(b[0]) if max(b[0]) >= max(b[1]) else max(b[1])
max_of_b = np.max(b)
print(max_of_b)

8


In [106]:
# # Exercise 4 - refactor the following using numpy to find the mean of b
# mean_of_b = (sum(b[0]) + sum(b[1])) / (len(b[0]) + len(b[1]))
mean_of_b = np.mean(b)
print(mean_of_b)

5.5


In [107]:
# # Exercise 5 - refactor the following to use numpy for calculating the product of all numbers multiplied together.
# product_of_b = 1
# for row in b:
#     for number in row:
#         product_of_b *= number
product_of_b = np.product(b)
print(product_of_b)

20160


In [109]:
# # Exercise 6 - refactor the following to use numpy to find the list of squares 
# squares_of_b = []
# for row in b:
#     for number in row:
#         squares_of_b.append(number**2)

squares_of_b = np.square(b)
print(squares_of_b)

[[ 9 16 25]
 [36 49 64]]


In [110]:
# # Exercise 7 - refactor using numpy to determine the odds_in_b
# odds_in_b = []
# for row in b:
#     for number in row:
#         if(number % 2 != 0):
#             odds_in_b.append(number)
odds_in_b = b[b%2 != 0]
print(odds_in_b)

[3 5 7]


In [111]:
#  Exercise 8 - refactor the following to use numpy to filter only the even numbers
# evens_in_b = []
# for row in b:
#     for number in row:
#         if(number % 2 == 0):
#             evens_in_b.append(number)

evens_in_b = b[b%2 ==0]
print(evens_in_b )

[4 6 8]


In [103]:
# Exercise 9 - print out the shape of the array b.
print(b.shape)


(2, 3)


In [100]:
# Exercise 10 - transpose the array b.
transpose_b = np.transpose(b)
print(transpose_b)


[[3 6]
 [4 7]
 [5 8]]


In [99]:
# Exercise 11 - reshape the array b to be a single list of 6 numbers. (1 x 6)

single_array = np.reshape(b,(1,6))
print(single_array)




[[3 4 5 6 7 8]]


In [98]:
# Exercise 12 - reshape the array b to be a list of 6 lists, each containing only 1 number (6 x 1)
new_array = np.reshape(b,(6,1))
print(new_array)

[[3]
 [4]
 [5]
 [6]
 [7]
 [8]]


In [ ]:
## Setup 3
c = [
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
]

In [140]:
# SETUP 3

import numpy as np

c = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [113]:
# Exercise 1 - Find the min, max, sum, and product of c.
np.min(c), np.max(c), np.sum(c), np.product(c)



(1, 9, 45, 362880)

In [119]:
# Exercise 2 - Determine the standard deviation of c.

np.std(c)

2.581988897471611

In [120]:
# Exercise 3 - Determine the variance of c.

np.var(b)


2.9166666666666665

In [115]:
# Exercise 4 - Print out the shape of the array c
print(c.shape)




(3, 3)


In [123]:
# Exercise 5 - Transpose c and print out transposed result.

transpose_c = np.transpose(c)
print(transpose_c)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [141]:
# Exercise 6 - Get the dot product of the array c with c. 

c.dot(c)

array([[ 30,  36,  42],
       [ 66,  81,  96],
       [102, 126, 150]])

In [134]:
# Exercise 7 - Write the code necessary to sum up the result of c times c transposed. Answer should be 261

np.sum(c *(transpose_c))


261

In [135]:
# Exercise 8 - Write the code necessary to determine the product of c times c transposed. Answer should be 131681894400.

np.product(c *(transpose_c))

131681894400

In [ ]:
# ## Setup 4
# d = [
#     [90, 30, 45, 0, 120, 180],
#     [45, -90, -30, 270, 90, 0],
#     [60, 45, -45, 90, -45, 180]
# ]

In [142]:
import numpy as np

d = np.array([
    [90, 30, 45, 0, 120, 180],
    [45, -90, -30, 270, 90, 0],
    [60, 45, -45, 90, -45, 180]
])

In [143]:
# Exercise 1 - Find the sine of all the numbers in d

np.sin(d)

array([[ 0.89399666, -0.98803162,  0.85090352,  0.        ,  0.58061118,
        -0.80115264],
       [ 0.85090352, -0.89399666,  0.98803162, -0.17604595,  0.89399666,
         0.        ],
       [-0.30481062,  0.85090352, -0.85090352,  0.89399666, -0.85090352,
        -0.80115264]])

In [144]:
# Exercise 2 - Find the cosine of all the numbers in d
np.cos(d)


array([[-0.44807362,  0.15425145,  0.52532199,  1.        ,  0.81418097,
        -0.59846007],
       [ 0.52532199, -0.44807362,  0.15425145,  0.98438195, -0.44807362,
         1.        ],
       [-0.95241298,  0.52532199,  0.52532199, -0.44807362,  0.52532199,
        -0.59846007]])

In [145]:
# Exercise 3 - Find the tangent of all the numbers in d

np.tan(d)

array([[-1.99520041, -6.4053312 ,  1.61977519,  0.        ,  0.71312301,
         1.33869021],
       [ 1.61977519,  1.99520041,  6.4053312 , -0.17883906, -1.99520041,
         0.        ],
       [ 0.32004039,  1.61977519, -1.61977519, -1.99520041, -1.61977519,
         1.33869021]])

In [146]:
# Exercise 4 - Find all the negative numbers in d

d[d < 0]

array([-90, -30, -45, -45])

In [147]:
# Exercise 5 - Find all the positive numbers in d

d[d > 0]

array([ 90,  30,  45, 120, 180,  45, 270,  90,  60,  45,  90, 180])

In [153]:
# Exercise 6 - Return an array of only the unique numbers in d.
np.unique(d)


array([-90, -45, -30,   0,  30,  45,  60,  90, 120, 180, 270])

In [152]:
# Exercise 7 - Determine how many unique numbers there are in d.

len(np.unique(d))

11

In [148]:
 #Exercise 8 - Print out the shape of d.

print(d.shape)

(3, 6)


In [149]:
# Exercise 9 - Transpose and then print out the shape of d.

T = np.transpose(d)
print(T.shape)

(6, 3)


In [151]:
# Exercise 10 - Reshape d into an array of 9 x 2
np.reshape(d,(9,2))



array([[ 90,  30],
       [ 45,   0],
       [120, 180],
       [ 45, -90],
       [-30, 270],
       [ 90,   0],
       [ 60,  45],
       [-45,  90],
       [-45, 180]])